easy_admin:
    entities:
        Pages:
            class: DMB\BlogBundle\Entity\Page
            label: 'Pages statiques'
            help: 'Attention seules les pages en position 1 et 2 seront ajoutées.'


            list:
              title: "Toutes les pages"
              fields:
                - {property: 'title', label: 'Titre de la page'}

            form:
              fields:
                - {property: 'title', type: 'text'}
                - { property: 'position' , type: 'integer' }
                - {property: 'content', type: 'ckeditor' }