easy_admin:
    entities:
        Pages:
            class: DMB\BlogBundle\Entity\Page
            label: 'Static Pages'
            help: 'Warning.post.page'


            list:
              title: "All pages"
              fields:
                - {property: 'title', label: 'Page title'}

            form:
              fields:
                - {property: 'title', type: 'text'}
                - { property: 'position' , type: 'integer' }
                - {property: 'content', type: 'ckeditor' }