<?php

namespace DMB\UserBundle\Repository;

/**
 * UserAvatarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAvatarRepository extends \Doctrine\ORM\EntityRepository
{
}
