<?php

namespace DMB\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActiveUsers()
    {
        return $this->createQueryBuilder('user')
            ->where("user.enabled = true")
            ->getQuery()
            ->getResult();
    }
}
