imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: easyadmin/ }
    - { resource: pagination.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.cover_images: /uploads/images/covers
    app.path.avatar_images: /uploads/images/avatars
    posts_cache_type: file_system


framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
#        assets_base_url: "http://http://localhost:8000/"
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        session_name: blogjeanforteroche
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true


# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        # other form themes
        - 'DMBUserBundle:Form:fields.html.twig'


# Doctrine Configuration
doctrine:
    dbal:
        connections:
          # A collection of different named connections (e.g. default, conn2, etc)
          default:
              dbname:               '%database_name%'
              host:                 '%database_host%'
              port:                 '%database_port%'
              user:                 '%database_user%'
              password:             '%database_password%'
              charset:              UTF8
              path:                 ~
              memory:               ~

              # The unix socket to use for MySQL
              unix_socket:          ~

              # True to use as persistent connection for the ibm_db2 driver
              persistent:           ~

              # The protocol to use for the ibm_db2 driver (default to TCPIP if omitted)
              protocol:             ~

              # True to use dbname as service name instead of SID for Oracle
              service:              ~

              # The session mode to use for the oci8 driver
              sessionMode:          ~

              # True to use a pooled server with the oci8 driver
              pooled:               ~

              # Configuring MultipleActiveResultSets for the pdo_sqlsrv driver
              MultipleActiveResultSets:  ~
              driver:               pdo_mysql
              platform_service:     ~

              # the version of your database engine
              server_version:       5.6
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: DMB\UserBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
      confirmation:
        enabled: true
      form:
        type: DMB\UserBundle\Form\Type\RegistrationType
    profile:
      form:
        type: DMB\UserBundle\Form\Type\ProfileFormType



vich_uploader:
    db_driver: orm
    mappings:
            cover_images:
                uri_prefix:         '%app.path.cover_images%'
                upload_destination: '%kernel.root_dir%/../web/uploads/images/covers'
            avatar_images:
                uri_prefix:         '%app.path.avatar_images%'
                upload_destination: '%kernel.root_dir%/../web/uploads/images/avatars'


doctrine_cache:
  aliases:
    posts_cache : posts_cache
  providers:
    posts_cache:
      type: %posts_cache_type%
