# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.form.registration:
        class: DMB\UserBundle\Form\RegistrationType
        tags:
          - { name: form.type, alias: app_user_registration }
    app.form.editprofile:
        class: DMB\UserBundle\Form\ProfileFormType
        tags:
          - { name: form.type, alias: app_user_modification }
    dmb_blog.sendemail:
        class: DMB\BlogBundle\Service\sendEmail
        arguments: ['@mailer', '@templating']
    dmb_blog.checkcache:
        class: DMB\BlogBundle\Service\checkCache
        arguments: ['@posts_cache', '@dmb_blog.checkpath']
    dmb_blog.getchapternavigation:
        class: DMB\BlogBundle\Service\getChapterNavigation
        arguments: ['@dmb_blog.checkcache', '@doctrine.orm.entity_manager']
    dmb_blog.checkpath:
        class: DMB\BlogBundle\Service\checkPath
    dmb_blog.commentsmanagement:
        class: DMB\BlogBundle\Service\commentsManagement
        arguments: ['@doctrine.orm.entity_manager']
