# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    fos_user.doctrine_registry:
        alias: doctrine

    app.form.registration:
                    class: DMB\UserBundle\Form\RegistrationType
                    tags:
                        - { name: form.type, alias: app_user_registration }

    admin.post:
            class: DMB\BlogBundle\Admin\PostAdmin
            arguments: [~, DMB\BlogBundle\Entity\Post, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Chapitre }

