# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.form.registration:
        class: DMB\UserBundle\Form\RegistrationType
        tags:
          - { name: form.type, alias: app_user_registration }
    app.form.editprofile:
        class: DMB\UserBundle\Form\ProfileFormType
        tags:
          - { name: form.type, alias: app_user_modification }
    dmb_blog.sendemail:
        class: DMB\BlogBundle\Service\sendEmail
        arguments: ['@mailer', '@templating']
    dmb_blog.checkcache:
        class: DMB\BlogBundle\Service\checkCache
        arguments: ['@posts_cache']
    dmb_blog.getchapternavigation:
        class: DMB\BlogBundle\Service\getChapterNavigation
        arguments: ['@posts_cache']
