<?php

namespace DMB\BlogBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTwoPages()
    {
        return $this->findBy(array(), array('position' => 'ASC'), $limit = 2);
    }
}
