<?php

namespace DMB\BlogBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTwoPages()
    {
        return $this->createQueryBuilder('page')
            ->where('page.position IS NOT NULL')
            ->orderBy("page.position")
            ->setMaxResults(2)
            ->getQuery()
            ->getResult();
    }
}
