<?php

namespace DMB\BlogBundle\Repository;

/**
 * postRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class postRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActivePosts()
    {
        return $this->createQueryBuilder('p')
            ->where("p.isActivated = true")
            ->getQuery()
            ->getResult();
    }
}
