<?php

namespace DMB\BlogBundle\Repository;
use Doctrine\Common\Collections;

/**
 * postRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class postRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActivePosts()
    {
        return $this->createQueryBuilder('p')
            ->where("p.isActivated = true")
            ->andWhere("p.publishedDate < CURRENT_TIMESTAMP()")
            ->getQuery()
            ->getResult();
    }

    //find next and previous for Admin
    public function findByIdChapterNumber($chapterNumber)
    {
        return $this->createQueryBuilder('p')
            ->where("p.chapterNumber = $chapterNumber")
            ->getQuery()
            ->getOneOrNullResult(); //use to fetch the object
    }

    //find next and previous for user
    public function findByIdChapterNumberUser($chapterNumber)
    {
        return $this->createQueryBuilder('p')
            ->where("p.chapterNumber = $chapterNumber")
            ->andWhere("p.isActivated = true")
            ->getQuery()
            ->getOneOrNullResult(); //use to fetch the object
    }

    //find next and previous for anon
    public function findByIdChapterNumberAnon($chapterNumber)
    {
        return $this->createQueryBuilder('p')
            ->where("p.chapterNumber = $chapterNumber")
            ->andWhere("p.isActivated = true")
            ->andWhere("p.isPremium = false")
            ->getQuery()
            ->getOneOrNullResult(); //use to fetch the object
    }


}
