services:
#    dmb_user.example:
#        class: DMB\UserBundle\Example
<<<<<<< HEAD
#        arguments: [@service_id, "plain_value", %parameter%]
=======
#        arguments: ["@service_id", "plain_value", "%parameter%"]
>>>>>>> EasyAdmin
