easy_admin:
    entities:
        Users:
          class: DMB\UserBundle\Entity\User
          label: 'Membres'
          list:
            title: "Tous les membres"
          edit:
            fields:
              - username
              - email
              - enabled
              - { property: 'plainPassword', type: 'text', type_options: { required: false} }
              - lastLogin
              - { property: 'imageFile', type: 'vich_image', type_options: { required: true } }
              # if administrators are allowed to edit users' passwords and roles, add this:
              - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'Membres': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN' } } }
          new:
            fields:
              - name
              - username
              - email
              - enabled
              - { property: 'plainPassword', type: 'text', type_options: { required: true} }
              - lastLogin
              # if administrators are allowed to edit users' passwords and roles, add this:
              - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'Membres': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN' } } }



